version: '3.8'

# DEVELOPMENT ONLY - DO NOT USE THESE CREDENTIALS IN PRODUCTION
# For production, use environment variables or Docker secrets
services:
  postgres:
    image: postgres:16
    container_name: iftta-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: iftta
      # WARNING: These are default development credentials only
      # For production, set these via environment variables:
      # POSTGRES_USER: ${POSTGRES_USER:-postgres}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # CHANGE THIS IN PRODUCTION
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d iftta"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB

volumes:
  postgres_data:
    driver: local