apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ifthisthenat.fullname" . }}
  labels:
    {{- include "ifthisthenat.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ifthisthenat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "ifthisthenat.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ifthisthenat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: EXTERNAL_BASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: external-base
            - name: ISSUER_DID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: issuer-did
            - name: HTTP_BIND_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: http-bind-addr
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: log-level
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: database-url
            - name: DATABASE_MAX_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: database-max-connections
            - name: DATABASE_MIN_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: database-min-connections
            {{- if .Values.config.redis.enabled }}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: redis-url
            {{- end }}
            {{- if .Values.config.jetstream.enabled }}
            - name: JETSTREAM_ENABLED
              value: "true"
            - name: JETSTREAM_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: jetstream-url
            - name: JETSTREAM_CONSUMER_COUNT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: jetstream-consumer-count
            - name: JETSTREAM_PARTITION_COUNT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: jetstream-partition-count
            {{- end }}
            - name: SCHEDULER_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: scheduler-enabled
            - name: AIP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: aip-hostname
            - name: AIP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: aip-client-id
            - name: AIP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: aip-client-secret
            - name: HTTP_COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: http-cookie-key
            - name: WEBHOOK_MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: webhook-max-retries
            - name: WEBHOOK_RETRY_DELAY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: webhook-retry-delay
            - name: BLUEPRINT_CACHE_TTL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: blueprint-cache-ttl
            - name: BLUEPRINT_CACHE_CAPACITY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: blueprint-cache-capacity
            - name: BLUEPRINT_CACHE_REFRESH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: blueprint-cache-refresh
            - name: PUBLISH_RECORD_COLLECTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ifthisthenat.fullname" . }}
                  key: publish-record-collections
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}